export type Level = 1 | 2 | 3 | 4 | 'verbs';

export interface WordData {
  id: string;
  word: string;
  letters: string[];
  englishMeaning: string;
}

export const LEVELS_DATA: Record<string, WordData[]> = {
  1: [
    { id: '1-1', word: 'అమల', letters: ['అ', 'మ', 'ల'], englishMeaning: 'Amala' },
    { id: '1-2', word: 'ఆట', letters: ['ఆ', 'ట'], englishMeaning: 'Play/Game' },
    { id: '1-3', word: 'ఇల', letters: ['ఇ', 'ల'], englishMeaning: 'Earth' },
    { id: '1-4', word: 'ఈల', letters: ['ఈ', 'ల'], englishMeaning: 'Whistle' },
    { id: '1-5', word: 'ఉమ', letters: ['ఉ', 'మ'], englishMeaning: 'Uma (Name)' },
    { id: '1-6', word: 'ఊయల', letters: ['ఊ', 'య', 'ల'], englishMeaning: 'Swing' },
    { id: '1-7', word: 'ఎర', letters: ['ఎ', 'ర'], englishMeaning: 'Bait' },
    { id: '1-8', word: 'ఏనుగు', letters: ['ఏ', 'ను', 'గు'], englishMeaning: 'Elephant' },
    { id: '1-9', word: 'ఐదు', letters: ['ఐ', 'దు'], englishMeaning: 'Five' },
    { id: '1-10', word: 'ఒకటి', letters: ['ఒ', 'క', 'టి'], englishMeaning: 'One' },
    { id: '1-11', word: 'ఓడ', letters: ['ఓ', 'డ'], englishMeaning: 'Ship' },
    { id: '1-12', word: 'కల', letters: ['క', 'ల'], englishMeaning: 'Dream' },
    { id: '1-13', word: 'గడ', letters: ['గ', 'డ'], englishMeaning: 'Pole' },
    { id: '1-14', word: 'చదరం', letters: ['చ', 'ద', 'ర', 'ం'], englishMeaning: 'Square' },
    { id: '1-15', word: 'జల', letters: ['జ', 'ల'], englishMeaning: 'Water' },
    { id: '1-16', word: 'తపాల', letters: ['త', 'పా','ల'], englishMeaning: 'Post' },
    { id: '1-17', word: 'దండ', letters:['దం','డ'], englishMeaning: 'garland'},
    { id: '1-18', word: 'తల', letters: ['త', 'ల'], englishMeaning: 'Head' },
    { id: '1-19', word: 'దర', letters: ['ద', 'ర'], englishMeaning: 'Price' },
    { id: '1-20', word: 'నగ', letters: ['న', 'గ'], englishMeaning: 'Jewel' },
    { id: '1-21', word: 'పలక', letters: ['ప', 'ల', 'క'], englishMeaning: 'Slate' },
    { id: '1-22', word: 'బలపం', letters: ['బ', 'ల', 'ప', 'ం'], englishMeaning: 'Slate Pencil' },
    { id: '1-23', word: 'మామ', letters: ['మా', 'మ'], englishMeaning: ' uncle' },
    { id: '1-24', word: 'యమ', letters: ['య', 'మ'], englishMeaning: 'Yama' },
    { id: '1-25', word: 'రమ', letters: ['ర', 'మ'], englishMeaning: 'Rama' },
    { id: '1-26', word: 'వల', letters: ['వ', 'ల'], englishMeaning: 'Net' },
    { id: '1-27', word: 'శనగ', letters: ['శ', 'న', 'గ'], englishMeaning: 'chickpea' },
    { id: '1-28', word: 'ఆరు', letters: ['ఆ', 'రు'], englishMeaning: 'Six' },
    { id: '1-29', word: 'సంత', letters: ['సం','త'], englishMeaning: 'market' },
    { id: '1-30', word: 'హల', letters: ['హ', 'ల'], englishMeaning: 'Plough' },
    { id: '1-32', word: 'అరక', letters:['అ','ర','క'], englishMeaning: 'plough'}
  ],
  2: [
    { id: '2-1', word: 'కిటికి', letters: ['కి', 'టి', 'కి'], englishMeaning: 'Window' },
    { id: '2-2', word: 'కుక్క', letters: ['కు', 'క్క'], englishMeaning: 'Dog' },
    { id: '2-3', word: 'కూర', letters: ['కూ', 'ర'], englishMeaning: 'Curry/Vegetable' },
    { id: '2-4', word: 'కైక', letters: ['కై', 'క'], englishMeaning: 'Kaika' },
    { id: '2-5', word: 'కొలను', letters: ['కొ', 'ల', 'ను'], englishMeaning: 'Pond' },
    { id: '2-6', word: 'కోట', letters: ['కో', 'ట'], englishMeaning: 'Fort' },
    { id: '2-7', word: 'గౌను', letters: ['గౌ', 'ను'], englishMeaning: 'frock' },
    { id: '2-8', word: 'ఘంట', letters: ['ఘ', 'ం', 'ట'], englishMeaning: 'Bell' },
    { id: '2-9', word: 'చిలుక', letters: ['చి', 'లు', 'క'], englishMeaning: 'Parrot' },
    { id: '2-10', word: 'చీమ', letters: ['చీ', 'మ'], englishMeaning: 'Ant' },
    { id: '2-11', word: 'జున్ను', letters: ['జు', 'న్ను'], englishMeaning: 'Cheese' },
    { id: '2-12', word: 'జెండా', letters: ['జె', 'ం', 'డా'], englishMeaning: 'Flag' },
    { id: '2-13', word: 'టోపీ', letters: ['టో', 'పీ'], englishMeaning: 'Cap' },
    { id: '2-14', word: 'డప్పు', letters: ['డ', 'ప్పు'], englishMeaning: 'Drum' },
    { id: '2-15', word: 'తాత', letters: ['తా', 'త'], englishMeaning: 'Grandfather' },
    { id: '2-16', word: 'తీగ', letters: ['తీ', 'గ'], englishMeaning: 'Wire/Vine' },
    { id: '2-17', word: 'దూరము', letters: ['దూ', 'ర', 'ము'], englishMeaning: 'Distance' },
    { id: '2-18', word: 'నౌక', letters: ['నౌ', 'క'], englishMeaning: 'Ship' },
    { id: '2-19', word: 'పాము', letters: ['పా', 'ము'], englishMeaning: 'Snake' },
    { id: '2-20', word: 'పీత', letters: ['పీ', 'త'], englishMeaning: 'Crab' },
    { id: '2-21', word: 'పులి', letters: ['పు','లి'], englishMeaning: 'Tiger' },
    { id: '2-22', word: 'పూవ్వు', letters: ['పూ','వ్వు'], englishMeaning: 'Flower' },
    { id: '2-23', word: 'కలము', letters: ['క','ల','ము'], englishMeaning: 'Pen' },
    { id: '2-24', word: 'పేరు', letters: ['పే', 'రు'], englishMeaning: 'Name' },
    { id: '2-25', word: 'పైసా', letters: ['పై', 'సా'], englishMeaning: 'Paisa' },
    { id: '2-26', word: 'పొట్టి', letters: ['పొ', 'ట్టి'], englishMeaning: 'Short' },
    { id: '2-27', word: 'పోటీ', letters: ['పో', 'టీ'], englishMeaning: 'Competition' },
    { id: '2-28', word: 'పౌడరు', letters: ['పౌ', 'డ', 'రు'], englishMeaning: 'Powder' },
    { id: '2-29', word: 'మేక', letters: ['మే', 'క'], englishMeaning: 'Goat' },
    { id: '2-30', word: 'రైతు', letters: ['రై', 'తు'], englishMeaning: 'Farmer' },
    ],
  3: [
    { id: '3-1', word: 'అక్క', letters: ['అ', 'క్క'], englishMeaning: 'Sister' },
    { id: '3-2', word: 'అగ్గి', letters: ['అ', 'గ్గి'], englishMeaning: 'Fire' },
    { id: '3-3', word: 'పచ్చ', letters: ['ప', 'చ్చ'], englishMeaning: 'Green/Relish' },
    { id: '3-4', word: 'గుజ్జు', letters: ['గు', 'జ్జు'], englishMeaning: 'Pulp' },
    { id: '3-5', word: 'మట్టి', letters: ['మ', 'ట్టి'], englishMeaning: 'Soil' },
    { id: '3-6', word: 'లడ్డూ', letters: ['ల', 'డ్డూ'], englishMeaning: 'Sweet Laddu' },
    { id: '3-7', word: 'అత్త', letters: ['అ', 'త్త'], englishMeaning: 'Aunt' },
    { id: '3-8', word: 'ముద్దు', letters: ['ము', 'ద్దు'], englishMeaning: 'Kiss' },
    { id: '3-9', word: 'అన్న', letters: ['అ', 'న్న'], englishMeaning: 'Brother' },
    { id: '3-10', word: 'అప్పు', letters: ['అ', 'ప్పు'], englishMeaning: 'Loan' },
    { id: '3-11', word: 'అబ్బ', letters: ['అ', 'బ్బ'], englishMeaning: 'Father/Expression' },
    { id: '3-12', word: 'అమ్మ', letters: ['అ', 'మ్మ'], englishMeaning: 'Mother' },
    { id: '3-13', word: 'అయ్య', letters: ['అ', 'య్య'], englishMeaning: 'Father/Sir' },
    { id: '3-14', word: 'కర్ర', letters: ['క', 'ర్ర'], englishMeaning: 'Stick' },
    { id: '3-15', word: 'పల్లె', letters: ['ప', 'ల్లే'], englishMeaning: 'Village' },
    { id: '3-16', word: 'మువ్వ', letters: ['ము', 'వ్వ'], englishMeaning: 'Anklet Bell' },
    { id: '3-17', word: 'విస్సు', letters: ['వి', 'స్సు'], englishMeaning: 'Annoyance' },
    { id: '3-18', word: 'మొగ్గ', letters: ['మొ', 'గ్గ'], englishMeaning: 'Bud' },
    { id: '3-19', word: 'చెట్టు', letters: ['చె', 'ట్టు'], englishMeaning: 'Tree' },
    { id: '3-20', word: 'పిట్ట', letters: ['పి', 'ట్ట'], englishMeaning: 'Bird' },
    { id: '3-21', word: 'బొమ్మ', letters: ['బొ', 'మ్మ'], englishMeaning: 'Toy/Picture' },
    { id: '3-22', word: 'బియ్యం', letters: ['బి', 'య్యం'], englishMeaning: 'Rice' },
    { id: '3-23', word: 'నిచ్చెన', letters: ['ని', 'చ్చె', 'న'], englishMeaning: 'Ladder' },
    { id: '3-24', word: 'మబ్బు', letters: ['మ', 'బ్బు'], englishMeaning: 'Cloud' },
    { id: '3-25', word: 'పెద్ద', letters: ['పె', 'ద్ద'], englishMeaning: 'Big' },
  ],
  4: [
    { id: '4-1', word: 'క్షీరం', letters: ['క్షీ', 'రం'], englishMeaning: 'Milk' },
    { id: '4-2', word: 'పక్షి', letters: ['ప', 'క్షి'], englishMeaning: 'Bird' },
    { id: '4-3', word: 'జ్ఞానం', letters: ['జ్ఞా', 'నం'], englishMeaning: 'Knowledge' },
    { id: '4-4', word: 'దృష్టి', letters: ['దృ', 'ష్టి'], englishMeaning: 'Vision' },
    { id: '4-5', word: 'సృష్టి', letters: ['సృ', 'ష్టి'], englishMeaning: 'Creation' },
    { id: '4-6', word: 'ప్రేమ', letters: ['ప్రే', 'మ'], englishMeaning: 'Love' },
    { id: '4-7', word: 'శ్రీ', letters: ['శ్రీ'], englishMeaning: 'Prosperity/Mr.' },
    { id: '4-8', word: 'స్కూలు', letters: ['స్కూ', 'లు'], englishMeaning: 'School' },
    { id: '4-9', word: 'స్త్రీ', letters: ['స్త్రీ'], englishMeaning: 'Woman' },
    { id: '4-10', word: 'స్వతంత్రం', letters: ['స్వ', 'తం', 'త్రం'], englishMeaning: 'Independence' },
    { id: '4-11', word: 'ప్రభావం', letters: ['ప్ర', 'భా', 'వం'], englishMeaning: 'Effect' },
    { id: '4-12', word: 'రాష్ట్రం', letters: ['రా', 'ష్ట్రం'], englishMeaning: 'State' },
    { id: '4-13', word: 'విజ్ఞానం', letters: ['వి', 'జ్ఞా', 'నం'], englishMeaning: 'Science' },
    { id: '4-14', word: 'ధర్మం', letters: ['ధ', 'ర్మం'], englishMeaning: 'Duty/Righteousness' },
    { id: '4-15', word: 'సందేశం', letters: ['సం', 'దే', 'శం'], englishMeaning: 'Message' },
    { id: '4-16', word: 'ముఖ్యము', letters: ['ము', 'ఖ్య', 'ము'], englishMeaning: 'Important' },
    { id: '4-17', word: 'నిత్యము', letters: ['ని', 'త్య', 'ము'], englishMeaning: 'Daily' },
    { id: '4-18', word: 'కార్యము', letters: ['కా', 'ర్య', 'ము'], englishMeaning: 'Task/Work' },
    { id: '4-19', word: 'స్నేహం', letters: ['స్నే', 'హం'], englishMeaning: 'Friendship' },
    { id: '4-20', word: 'ప్రశ్న', letters: ['ప్ర', 'శ్న'], englishMeaning: 'Question' },
  ],
  verbs: [
    { id: 'v-1', word: 'తిను', letters: ['తి', 'ను'], englishMeaning: 'Eat' },
    { id: 'v-2', word: 'నడువు', letters: ['న', 'డు', 'వు'], englishMeaning: 'Walk' },
    { id: 'v-3', word: 'చదువు', letters: ['చ', 'దు', 'వు'], englishMeaning: 'Read' },
    { id: 'v-4', word: 'పాడు', letters: ['పా', 'డు'], englishMeaning: 'Sing' },
    { id: 'v-5', word: 'పడుకో', letters: ['ప', 'డు', 'కో'], englishMeaning: 'Sleep' },
    { id: 'v-6', word: 'నవ్వు', letters: ['న', 'వ్వు'], englishMeaning: 'Laugh' },
    { id: 'v-7', word: 'చూడు', letters: ['చూ', 'డు'], englishMeaning: 'See/Look' },
    { id: 'v-8', word: 'పాడు', letters: ['పా','డు'], englishMeaning: 'Sing' },
    { id: 'v-9', word: 'పాడెను', letters: ['పా','డె','ను'], englishMeaning: 'Sang' },
    { id: 'v-10', word: 'పాడబడిన', letters: ['పా','డ','బ','డి','న'], englishMeaning: 'Sung' },
    { id: 'v-11', word: 'కదల్చు', letters: ['క','దల్చు'], englishMeaning: 'Shake' },
    { id: 'v-12', word: 'కదల్చెను', letters: ['క','దల్చె','ను'], englishMeaning: 'Shook' },
    { id: 'v-13', word: 'కదల్చబడిన', letters: ['క','దల్చ','బ','డి','న'], englishMeaning: 'Shaken' },
    { id: 'v-14', word: 'దూకు', letters: ['దూ','కు'], englishMeaning: 'Spring/Jump' },
    { id: 'v-15', word: 'దూకెను', letters: ['దూ','కె','ను'], englishMeaning: 'Sprang' },
    { id: 'v-16', word: 'దూకిన', letters: ['దూ','కి','న'], englishMeaning: 'Sprung' },
    { id: 'v-17', word: 'దొంగిలించు', letters: ['దొం','గి','లిం','చు'], englishMeaning: 'Steal' },
    { id: 'v-18', word: 'దొంగిలించెను', letters: ['దొం','గి','లిం','చె','ను'], englishMeaning: 'Stole' },
    { id: 'v-19', word: 'దొంగిలించబడిన', letters: ['దొం','గి','లిం','చ','బ','డి','న'], englishMeaning: 'Stolen' },
    { id: 'v-20', word: 'కుట్టు', letters: ['కు','ట్టు'], englishMeaning: 'Sting' },
    { id: 'v-21', word: 'కుట్టెను', letters: ['కు','ట్టె','ను'], englishMeaning: 'Stung' },
    { id: 'v-22', word: 'కుట్టిన', letters: ['కు','ట్టి','న'], englishMeaning: 'Stung' },
    { id: 'v-23', word: 'కొట్టు', letters: ['కొ','ట్టు'], englishMeaning: 'Strike' },
    { id: 'v-24', word: 'కొట్టెను', letters: ['కొ','ట్టె','ను'], englishMeaning: 'Struck' },
    { id: 'v-25', word: 'కొట్టిన', letters: ['కొ','ట్టి','న'], englishMeaning: 'Struck' },
    { id: 'v-26', word: 'పంపు', letters: ['పం','పు'], englishMeaning: 'Send' },
    { id: 'v-27', word: 'పంపెను', letters: ['పం','పె','ను'], englishMeaning: 'Sent' },
    { id: 'v-28', word: 'పంపిన', letters: ['పం','పి','న'], englishMeaning: 'Sent' },
    { id: 'v-29', word: 'నిద్రించు', letters: ['ని','ద్రిం','చు'], englishMeaning: 'Sleep' },
    { id: 'v-30', word: 'నిద్రించెను', letters: ['ని','ద్రిం','చె','ను'], englishMeaning: 'Slept' },
    { id: 'v-31', word: 'నిద్రించిన', letters: ['ని','ద్రిం','చి','న'], englishMeaning: 'Slept' },
    { id: 'v-32', word: 'తీసికొను', letters: ['తీ','సి','కొ','ను'], englishMeaning: 'Take' },
    { id: 'v-33', word: 'తీసికొనెను', letters: ['తీ','సి','కొ','నె','ను'], englishMeaning: 'Took' },
    { id: 'v-34', word: 'తీసికొనిన', letters: ['తీ','సి','కొ','ని','న'], englishMeaning: 'Taken' },
    { id: 'v-35', word: 'చింపు', letters: ['చిం','పు'], englishMeaning: 'Tear' },
    { id: 'v-36', word: 'చింపెను', letters: ['చిం','పె','ను'], englishMeaning: 'Tore' },
    { id: 'v-37', word: 'చింపబడిన', letters: ['చిం','ప','బ','డి','న'], englishMeaning: 'Torn' },
    { id: 'v-38', word: 'బోధించు', letters: ['బో','ధిం','చు'], englishMeaning: 'Teach' },
    { id: 'v-39', word: 'బోధించెను', letters: ['బో','ధిం','చె','ను'], englishMeaning: 'Taught' },
    { id: 'v-40', word: 'బోధించిన', letters: ['బో','ధిం','చి','న'], englishMeaning: 'Taught' },
    { id: 'v-41', word: 'ఆలోచించు', letters: ['ఆ','లో','చిం','చు'], englishMeaning: 'Think' },
    { id: 'v-42', word: 'ఆలోచించెను', letters: ['ఆ','లో','చిం','చె','ను'], englishMeaning: 'Thought' },
    { id: 'v-43', word: 'ఆలోచించిన', letters: ['ఆ','లో','చిం','చి','న'], englishMeaning: 'Thought' },
    { id: 'v-44', word: 'గెలుచు', letters: ['గె','లు','చు'], englishMeaning: 'Win' },
    { id: 'v-45', word: 'గెలిచెను', letters: ['గె','లి','చె','ను'], englishMeaning: 'Won' },
    { id: 'v-46', word: 'గెలిచిన', letters: ['గె','లి','చి','న'], englishMeaning: 'Won' },
    { id: 'v-47', word: 'నేయు', letters: ['నే','యు'], englishMeaning: 'Weave' },
    { id: 'v-48', word: 'నేసెను', letters: ['నే','సె','ను'], englishMeaning: 'Wove' },
    { id: 'v-49', word: 'నేసిన', letters: ['నే','సి','న'], englishMeaning: 'Woven' },
    { id: 'v-50', word: 'ధరించు', letters: ['ధ','రిం','చు'], englishMeaning: 'Wear' },
    { id: 'v-51', word: 'ధరించెను', letters: ['ధ','రిం','చె','ను'], englishMeaning: 'Wore' },
    { id: 'v-52', word: 'ధరించిన', letters: ['ధ','రిం','చి','న'], englishMeaning: 'Worn' },
    { id: 'v-53', word: 'వ్రాయు', letters: ['వ్రా','యు'], englishMeaning: 'Write' },
    { id: 'v-54', word: 'వ్రాసేను', letters: ['వ్రా','సే','ను'], englishMeaning: 'Wrote' },
    { id: 'v-55', word: 'వ్రాయబడిన', letters: ['వ్రా','య','బ','డి','న'], englishMeaning: 'Written' },
  ]
};

export const getRandomWord = (level: Level, excludeId?: string): WordData => {
  const words = LEVELS_DATA[level as string];
  const availableWords = words.filter(w => w.id !== excludeId);
  const targetWords = availableWords.length > 0 ? availableWords : words;
  const randomIndex = Math.floor(Math.random() * targetWords.length);
  return targetWords[randomIndex];
};

export const generateDistractorLetters = (correctLetters: string[], count: number = 3): string[] => {
  const allLetters = [
    'అ', 'ఆ', 'ఇ', 'ఈ', 'ఉ', 'ఊ', 'ఎ', 'ఏ', 'ఐ', 'ఒ', 'ఓ', 'ఔ',
    'క', 'ఖ', 'గ', 'ఘ', 'చ', 'ఛ', 'జ', 'ఝ', 'ట', 'ఠ', 'డ', 'ఢ',
    'త', 'థ', 'ద', 'ధ', 'న', 'ప', 'ఫ', 'బ', 'భ', 'మ',
    'య', 'ర', 'ల', 'వ', 'శ', 'ష', 'స', 'హ', 'ళ', 'క్ష', 'ఱ',
    'కి', 'టీ', 'పూ', 'దూ', 'రై', 'గౌ', 'క్క', 'మ్మ', 'న్న', 'ర్ర', 'ల్ల', 'స్త్రీ', 'స్కృ'
  ];
  
  const pool = allLetters.filter(l => !correctLetters.includes(l));
  const shuffledPool = [...pool].sort(() => 0.5 - Math.random());
  return shuffledPool.slice(0, count);
};
